services:
  # Node.js Backend Service
  app:
    build: .
    container_name: todo-app
    environment:
      - MONGO_URI=mongodb://mongo:27017/todo_app
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    networks:
      - todo-network

  # MongoDB Database Service
  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    networks:
      - todo-network
    volumes:
      - mongo-data:/data/db

  # Prometheus Service
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
    networks:
      - todo-network

  # Grafana Service
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin" # Set your admin password here
    ports:
      - "3000:3000" # Grafana accessible on port 3000
    volumes:
      - grafana-data:/var/lib/grafana # Persist Grafana data, dashboards, and config
      - ./grafana/provisioning:/etc/grafana/provisioning # For provisioning dashboards and datasources
    depends_on:
      - prometheus
    networks:
      - todo-network

volumes:
  mongo-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

networks:
  todo-network:
    driver: bridge
